const menu = [
  {
    id: 1,
    title: 'Pashupatinath Temple',
    category: 'kathmandu',
    price: "Free",
    img: './images/pashupatinath.jpg',
    desc: `Pashupathinath Temple is located on the banks of the divine Baramati River. Built in the 5th century, it is also a designated UNESCO World Heritage Site.`,
  },
  {
    id: 2,
    title: 'Nagarkot',
    category: 'Bhaktapur',
    price: 'Free',
    img: './images/nagarkot.jpg',
    desc: `It is also a paradise for hikers or adventure lovers as well as serenity seekers. Lots of budget-friendly homestays are also available here to enjoy a true nature vacation.`,
  },
  {
    id: 3,
    title: 'Chandragiri',
    category: 'kathmandu',
    price: '700 NPR',
    img: './images/chandragiri.jpg',
    desc: `Known for its cable car ride, Chandragiri Hills offer not only captivated views of the Himalayan ranges but a chance to feel rejuvenated amid a fresh environment.`,
  },
  {
    id: 4,
    title: 'Janaki Temple',
    category: 'dhanusa',
    price: "Free",
    img: './images/janaki.jpg',
    desc: `Janaki Temple is located in the Mithila district of Nepal and is dedicated to Goddess Sita. As per Hindu Mythology, it is the place where Sita was born and got married to God Rama.`,
  },
  {
    id: 5,
    title: 'The Boudhanath Stupa',
    category: 'kathmandu',
    price: 'Free',
    img: './images/bouddha.jpg',
    desc: `Boudhanath Stupa is one of the largest spherical stupas in the world. It is one of the most sacred shrines for Buddhists who visit the place to perform the Kora ritual.`,
  },
  {
    id: 6,
    title: 'Annapurna Base Camp',
    category: 'Kaski',
    price: 'Free',
    img: './images/abc.jpg',
    desc: `The 10th highest mountain in the world at approx. 8,091 metres. The entire massif is part of the largest conservation area of Nepal and is home to several world-class treks.`,
  },
  {
    id: 7,
    title: 'Chitwan National Park',
    category: 'chitwan',
    price: "150 NPR",
    img: './images/chitwan.jpg',
    desc: `Chitwan National Park houses a diverse variety of birds, wild animals, and flora. It serves as the protection centre for One Horned Rhinoceros, Gharial Crocodiles, and Royal Bengal Tigers.`,
  },
  {
    id: 8,
    title: 'Mt. Everest',
    category: 'solukhumbu',
    price: 'Free',
    img: './images/everest.jpg',
    desc: `Several rare and endangered species such as snow leopard, Himalayan black bear, red panda, musk deer, Himalayan wolves, etc., are also found in the region.`,
  },
  {
    id: 9,
    title: 'Ilam',
    category: 'illam',
    price: "Free",
    img: './images/illam.jpg',
    desc: `Ilam is known for its tea gardens, lush woods, majestic hills, and friendly ambience. This region is rich in cultural diversity, natural scenery, and spices & tea estates.`,
  },
  {
    id: 10,
    title: 'Koshi Tappu',
    category: 'eastern terai',
    price: "100 NPR",
    img: './images/koshitappu.jpg',
    desc: `The reserve is home to various wild animals and exotic birds, including native and migratory, various species of fishes, Ganges dolphins, and Gharial crocodiles.`,
  },
  {
    id: 11,
    title: 'Phewa Lake',
    category: 'Kaski',
    price: "500 NRP",
    img: './images/phewa.jpg',
    desc: `Phewa Lake features the perfect settings for experiencing boating through calm turquoise blue waters. An island in the middle of the lake has ancient Tal Barahi Temple.`,
  },
  {
    id: 12,
    title: 'Maya Devi Temple',
    category: 'Rupandehi',
    price: "500 NRP",
    img: './images/mayadevi.jpg',
    desc: `The temple houses the archaeological remains dating back to the Ashoka era, around 3rd century BCE that document the place being the birthplace of Lord Buddha.`,
  },
];
export default menu;
